namespace Egnyte.Api.Users
{
    public class UserUpdate
    {
        /// <summary>
        /// Required. An opaque, immutable, unique identifier for the user, generated by Egnyte.
        /// This identifier is used to refer to the user in all API calls.
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// Optional. The email address of the user. Any valid email address (e.g. admin@acme.com).
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Optional. The last name of the user. Any plain text (e.g. Smith).
        /// </summary>
        public string FamilyName { get; set; }

        /// <summary>
        /// Optional. The first name of the user. Any plain text (e.g. John).
        /// </summary>
        public string GivenName { get; set; }

        /// <summary>
        /// Optional. Whether the user is active or inactive.
        /// </summary>
        public bool? Active { get; set; }

        /// <summary>
        /// Optional. If set to true when creating a user,
        /// an invitation email will be sent (if the user is created in active state).
        /// </summary>
        public bool? SendInvite { get; set; }

        /// <summary>
        /// Optional. The authentication type for the user.
        /// </summary>
        public UserAuthType? AuthType { get; set; }

        /// <summary>
        /// Optional. The type of the user.
        /// </summary>
        public UserType? UserType { get; set; }

        /// <summary>
        /// Optional. Only required if the user is SSO authenticated and not using default user mapping.
        /// Do not specify if user is not SSO authenticated. This is the way the user is identified within
        /// the SAML Response from an SSO Identity Provider, i.e. the SAML Subject (e.g. jsmith)
        /// </summary>
        public string IdpUserId { get; set; }

        /// <summary>
        /// Optional. Do not specify if user is not AD authenticated. Used to bind child authentication policies
        /// to a user when using Active Directory authentication in a multi-domain setup (e.g. jmiller@example.com)
        /// </summary>
        public string UserPrincipalName { get; set; }
    }
}
