namespace Egnyte.Api.Users
{
    public class ExistingUser : User
    {
        /// <summary>
        /// An opaque, immutable, unique identifier for the user, generated by Egnyte.
        /// This identifier is used to refer to the user in all API calls.
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// If user is locked.
        /// </summary>
        public bool Locked { get; set; }
    }
}
