on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install OpenSSL 1.1
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build